server:
  port: 8080

spring:
  application:
    name: user-project
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

app:
  jwt:
    expiration: 3600000
  password:
    regex: ^(?=.*[A-Z])(?=.*\\d).{5,}$

spring-doc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html 